# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

workflows:
  failing_when:
    jobs:
      - failing_job

jobs:
  failing_job:
    <<: *defaults
    steps:
      - run: return 1
      - run: 
          name: on error
          command: echo "Hello Error!"
          when: on_fail